eclipse-tractusx/portal-assets

developer/Technical Documentation/Others/Images, Graphics and Diagrams.md, public/assets/images/docs/graphics/image-formats.svg, public/assets/images/docs/graphics/image-formats.svg.license
Documenting best practices for images in web applications.
Not all developers are familiar with the process to choose the best image format or encoding. We provide a description of best practices to assist.
No Github issue, Jira CPLP-2525
=> improve(documentation): add best practices for images

DEPENDENCIES, yarn.lock
Upgrade the dependent libraries to latest version.
Dependent libraries are updated regularly from their developers. Using always the latest bugfixes is a good practice to reduce the risk of security issues and application bugs.
N/A
=> chore(docs): yarn upgrade

public/assets/content/de/usecase.json
removed extra space which was causing parsing issue
usecase section is not loading for DE
NA
=> bugfix(json) : removed extra space and format json

public/documentation/css/Main.css, public/documentation/js/Main.js
Home page should work in web, tab and mobile browsers as well. Update the styles wrt the browser size.
Not able to use it in mobile browser or small browsers
NA
=> updates(home): update style wrt mobile browser

CHANGELOG.md, DEPENDENCIES, package.json
merge release branch in main for 1.5.0-RC1 version.
to wrap up release process main for 1.5.0-RC1 version.
n/a
=> release(1.5.0-RC1): merge release in main

docs/01. Onboarding/01. Registration Invite/index.md, docs/01. Onboarding/02. Registration/index.md, docs/01. Onboarding/03. Registration Approval/index.md
Enhanced index.md file for end user documentation with an table of content:
- 01.Onboarding/01.Registration Invite
- 01.Onboarding/02.Registration
- 01.Onboarding/03.Registration Approval
Index files missed the table of content/direct links to sub-chapters
n/a
=> docs(portal-user): add index files

public/documentation/js/Main.js
Fixing Sonar Cloud Bugs
To improve the analytics
CPLP-2793
=> fix(sonar bugs): add catch statement to promises

docs/02. Technical Integration/04. Dataspace Discovery/01. Open API.md
Enhance API Docu for Connector Discovery
Endpoint details have been updated.
n/a
=> Enhance endpoint details

public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
Attribute name should be title instead of linkName
subnavigation title not appearing
=> bugfix(company roles): fix sub navigation attribute name

docs/Style-Guide/button load more.md, docs/Style-Guide/button.md, docs/Style-Guide/date picker.md, docs/Style-Guide/drop down.md, docs/Style-Guide/dropzone.md, docs/Style-Guide/input field.md, docs/Style-Guide/loading.md, docs/Style-Guide/scrollbar.md, docs/Style-Guide/searchbar.md, docs/Style-Guide/toast message.md
Documentation of the shared-component-elements
Documentation of the portal and shared ui components to build a transparent understanding of the implemented components, usage guidelines, etc.
n/a
=> UI Component Templates

developer/02. Technical Integration/01. Connector Registration/02. View Connector.md
Documentation of the new "Managed Connector" view in the Technical Integration/Connector Management section inside the portal.
Documentation of the new "Managed Connector" view in the Technical Integration/Connector Management section inside the portal.
n/a
=> Add managed connector description

docs/02. Technical Integration/01. Connector Registration/08. Policy Management.md
new content policy management added under connector registration.
new content
NA
=> updates(documentation): add new content policy management

.github/workflows/release_candidate.yml, CHANGELOG.md, package.json
Merge release 1.6.0-RC1 branch into main
To have the latest branch available in the main branch the release branch is merged into the branch
N/A
=> release(1.6.0-RC1): merge release into main

developer/04. Apps/06. App Change Process/03. App Instance Url.md, docs/04. App(s)/06. App Change Process/03. Change App Tenant URL.md
Documentation of app instance url change process
New developed feature
n/a
=> chore: enhance documentation for app instance url change

docs/06. Notifications/01. Notifications/01. Overview.md
User docu for "Notifications"
User docu for "Notifications"
n/a
=> chore: add notification documentation

developer/02. Technical Integration/01. Connector Registration/03. Create new Connector Registration.md, docs/02. Technical Integration/01. Connector Registration/02. Connector Registration.md, docs/02. Technical Integration/01. Connector Registration/06. OpenAPI.md
Connector registration docu updated
Implementation updates
n/a
=> chore: adjust managed connector details

CHANGELOG.md, package.json
Bump the version and update the change log for release v1.6.0-RC2
To have the correct version in the release branch
N/A
=> release: bump version for v1.6.0-RC2

CHANGELOG.md, developer/01. Onboarding/03. Registration Approval/03. Registration Approval Process.md, developer/02. Technical Integration/01. Connector Registration/03. Create new Connector Registration.md, developer/02. Technical Integration/04. Credentials/00. Wallet Creation.md, developer/02. Technical Integration/04. Credentials/01. Get UseCase Credential.md, developer/02. Technical Integration/04. Credentials/02. Other Certificates.md, developer/04. Apps/06. App Change Process/03. App Instance Url.md, docs/01. Onboarding/03. Registration Approval/03. Registration Approval Process.md, docs/02. Technical Integration/01. Connector Registration/02. Connector Registration.md, docs/02. Technical Integration/01. Connector Registration/06. OpenAPI.md, docs/04. App(s)/06. App Change Process/03. Change App Tenant URL.md, docs/06. Certificates/01. UseCase Participation.md, docs/06. Certificates/02. Other Certificates.md, docs/06. Notifications/01. Notifications/01. Overview.md, package.json
Merge release into main
To have the latest changes available in main
N/A
=> release(1.6.0-RC2): merge release into main

public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
change url for use case frame work and company certificates. remove unwanted links in sub sections
urls pointing to wrong pages
NA
=> updates(participant): url and content

public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
use Catena-X instead of catena-x
Typo
NA
=> bugfix(company roles): typo fixes

public/documentation/css/Chapter.css
adjust the height of the side menu
bottom most items are not visible. side menu not fully scrolls to bottom
NA
=> bugfix(help section): fix scroll issue

developer/03. User Management/03. Technical User/01. Summary.md, developer/03. User Management/03. Technical User/02. View Technical Users.md, developer/03. User Management/03. Technical User/04. Delete Technical User.md, docs/03. User Management/03. Technical User/01. Technical User Overview.md, docs/03. User Management/03. Technical User/03. Delete Technical User.md
Managed Technical User Details for Provider and Owner added
Functional enhancement to allow user handling by owners and providers.
n/a
=> chore: add managed tech user details

developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
Added documentation for the daps removal
to document the latest database changes
N/A - Jira Issue: CPLP-3105
=> chore: add remove daps docu

CHANGELOG.md, package.json
update changelog for v1.6.0-RC5
bump version for v1.6.0-RC5
To prepare for the release
N/A
=> release: update changelog for v1.6.0-RC5

docs/02. Technical Integration/01. Connector Registration/08. Policy Management.md, public/assets/content/de/dataspace.json, public/assets/content/en/dataspace.json
update the policy documentation
to have the process well documented
n/a
=> chore: policy documentation

developer/Technical Documentation/Others/Notifications.md
Notification type documentation enhanced by adding new released and supported notification
With the development of new features we also implemented new notification messages/types which got added inside the developer docu
n/a
=> chore: notification type documentation

developer/Technical Documentation/Interface Contracts/BPDM.md
Updated bpdm
to have the latest documentation for bpdm
n/a
=> chore: update bpdm

developer/Technical Documentation/Dev Process/Shared Components.md
Document developing shared components
Developers should know the recommended process.
ref. Jira CLPLP-2929
=> improve(docs): add description about developing shared components

developer/Technical Documentation/Operations/Release-Process.md
update release process
there were a couple of changes to the release process in the last months
n/a
=> docs: update release process

docs/02. Technical Integration/01. Connector Registration/index.md, docs/02. Technical Integration/02. Identity Provider Management/index.md, docs/02. Technical Integration/03. CX Membership/index.md, docs/02. Technical Integration/04. Dataspace Discovery/index.md, docs/02. Technical Integration/05. Company Role/index.md, docs/03. User Management/02. Modify User Account/06. Delete User.md, docs/03. User Management/02. Modify User Account/index.md, docs/03. User Management/03. Technical User/index.md, docs/03. User Management/04. Assign App Roles/index.md, docs/03. User Management/index.md, docs/04. App(s)/01. Marketplace/05. FAQ.md, docs/04. App(s)/02. App Release Process/index.md, docs/04. App(s)/index.md, docs/05. Service(s)/02. Service Release Process/index.md, docs/05. Service(s)/03. Service Subscription/01. Service Subscription.md, docs/05. Service(s)/index.md, docs/06. Certificates/index.md
Please include a summary of the change.
Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.
=> Add End User Index.md files

public/documentation/js/Main.js
Fix broken links in documentation
Users expect links pointing to correct pages
ref: Jira CPLP-2332
=> bugfix(documentation): fix broken links

developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
Added Information about new table language_long_names
It help developers and dn users to know about schema and its usage
CPLP-1302
reas
=> docs: add migration info for language_long_names table

public/assets/content/de/dataspace.json, public/assets/content/en/dataspace.json
fix json error which is braking the data space whole page
data space page is broken
NA
=> fix(dataspace): solve json error

.github/workflows/release-release_candidate.yml, .github/workflows/release.yml, SECURITY.md
- update security.md
- update npm version action
- https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file
- https://github.com/martinbeentjes/npm-get-version-action
=> chore: update security.md and GH action

developer/Technical Documentation/Architecture/Building block view.md, developer/Technical Documentation/Architecture/Development Concept.md, developer/Technical Documentation/Identity & Access/10. FAQ.md, developer/Technical Documentation/Interface Contracts/Clearinghouse.md, developer/Technical Documentation/Interface Contracts/Managed Wallets.md
enhance technical documentation
n/a
=> docs: enhance technical documentation

.github/workflows/release-release_candidate.yml, .github/workflows/release.yml, .github/workflows/release_candidate.yml, CHANGELOG.md, DEPENDENCIES, package.json
Merge the latest release changes from v1.6.1 into main
to have the latest changes of v1.6.1 available in the main branch
N/A
=> release(1.6.1): merge release into main

DEPENDENCIES, yarn.lock
Upgrade all dependencies
Using the latest bugfix releases reduces the risk of bugs and potential security issues.
n/a
=> chore(deps): upgrade dependencies

public/assets/content/de/dataspace.json, public/assets/content/en/dataspace.json
to keep uniformity in the portal app, use white bg in the last section of every static page sections.
footer shows different variations
=> updates(static page): update background color

DEPENDENCIES, public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
update app provider content
add new section osp
content update
NA
=> updates(company roles): content update

public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
use proper links in help section.
links are not valid
NA
=> updates(company roles): add proper links 

developer/Technical Documentation/DB Views and Details/Data Management.md
Please include a summary of the change.
Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.
=> Update Data Management.md

developer/Technical Documentation/Operations/Auditing.md
Updated the documentation for the database auditing
The implementation of the auditing changed
N/A - Jira Issue: CPLP-3100
[#203](https://github.com/eclipse-tractusx/portal-backend/pull/203)
=> feat(audit): adjust documentation

CHANGELOG.md, package.json
Merge the latest release changes from v1.7.0-RC1 into main
to have the latest changes of v1.7.0-RC1 available in the main branch
N/A
=> release(v1.7.0-RC1): merge release into main

.github/workflows/trivy-main.yml, .github/workflows/trivy.yml
fix trivy: don't fail on high findings
action should only fail if there is an error/misconfiguration
relates to https://github.com/eclipse-tractusx/portal-frontend/pull/353
=> fix(trivy): don't fail on high findings

developer/Technical Documentation/Architecture/Security-Assessment.md
updates to correct the diagram and changes to improve displaying of mermaid diagram
https://github.com/eclipse-tractusx/portal-assets/pull/193
=> docs(data flow): add diagram

docs/09. Others/12. Offer Authentication Flow.md
add offer authentication flow description
To have a documentation for the topic
N/A
=> docs: update offer authentication flow

developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
Add script to add technical user profiles to offers (apps) which don't have any
The Autosetup process requires apps to have an technical user profiles and fails if an app doesn't have a technical user profile set
N/A
=> chore: update upgrade script for technical user profiles

developer/Technical Documentation/Architecture/Security-Assessment.md
add information about penetration testing.
enhance information about the executed security assessment.
=> docs: add information about penetration testing

.github/workflows/checks.yml
execute linter and build checks at pull request
add automatic checks
relates to https://github.com/eclipse-tractusx/portal-assets/pull/178
=> chore: execute checks at pull request

.github/workflows/release-release_candidate.yml, .github/workflows/release.yml
add additional image tags of type semver
https://github.com/eclipse-tractusx/portal-assets/issues/206
=> build(release): add additional image tags of type semver

docs/developer/03. User Management/03. Technical User/02. View Technical Users.md, docs/user/03. User Management/03. Technical User/01. Technical User Overview.md
Added documentation of the endpoint functional enhancement to support the request of inactive technical users connected to the own company
Feature enhancement
n/a
=> docs: enhance technical user view

docs/developer/04. Apps/02. App Release Process/App Release Process.md, docs/developer/05. Service(s)/02. Service Release Process/03.Terms&Conditions.md, docs/user/04. App(s)/02. App Release Process/03. Terms&Conditions.md, docs/user/05. Service(s)/02. Service Release Process/03. Terms&Conditions.md
Update the 
- service release process
- app release process
documentation for user and developer docu to cover the latest changes of the conformity document upload as well as improving the existing documentation of the terms & conditions section.
Feature enhancement & documentation improvements
n/a
=> docs: improve offer release process conformity

docs/developer/01. Registration/02. Registration Portal/05. Document Upload.md
Updated registration details for status change
Documentation enhancement
#255 
=> docs(developer): registration process enhancement by incl. status endpoint

docs/developer/01. Registration/02. Registration Portal/05. Document Upload.md
Run pretty on document upload
To prettify the file
N/A
=> chore: adjust document upload

docs/user/08. Certificate Management/00. Summary.md, docs/user/08. Certificate Management/01. Certificate Upload.md, docs/user/08. Certificate Management/02. Certificate Deletion.md, docs/user/08. Certificate Management/03. Certificate Publishing.md
Add Certificate Management user documentation of the new supported features
Add new feature documentation
#255
=> docs(user): add company certificate management details

docs/developer/00. Personas/05. Onboarding Service Provider.md, docs/developer/01. Registration/01. Registration Process/02. Registration External.md
- added OSP persona description
- removed duplication
- added missing sections to cover complete external registration workflow steps
Extending OSP documentation
#255
=> docs(developer): extend osp documentation

docs/developer/01. Registration/02. Registration Portal/02. Add Company Data.md, docs/user/01. Onboarding/02. Registration/02. Add Company Data.md
Updated user and developer documentation of the registration process step 'Add company data'
Prettier & add additional  feature details of the endpoint for countryList static data
#255
=> docs: update registration process step 'Add company data'

public/assets/content/de/companyRoleChange.json, public/assets/content/en/companyRoleChange.json
Add Onboarding Service Provider content in company role change
To display message
https://github.com/eclipse-tractusx/portal-frontend/issues/544
=> feat(companyrole): add content for companyrole change

public/assets/content/de/dataspace.json, public/assets/content/en/dataspace.json
add additional description and link in policy intro section.
change content in use case section and show them in a bullet points
new change request
#575
=> fix(data space): update use case and policy intro section content

docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
add improvements to db-dependency of helm chart to upgrade details
https://github.com/eclipse-tractusx/portal/issues/191
=> docs(upgrade): add improvements to db-dependency of helm chart

public/documentation/js/Settings.js, src/documentation/Release.js
update pattern.
use openSync method to read the file before readFileSync
security check failed
NA
=> fix(codeql): fix security issues

public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
fix color of the first content section
the conformity body has no standards which need to get followed; due to that the standard content and table is not necessary
currently having the same color as the header, please update
#299 
=> fix(conformity): content update

DEPENDENCIES, docs/user/00. Personas/Onboarding Service Provider (OSP).md
Adding a persona of an osp from user pov.
Improve understanding of what OSPs are, what there purpose is and how you can find/access them.
=> docs(user): osp persona invitee pov

docs/developer/08. Certificate Management/03. Certificate Publishing.md, docs/developer/Technical Documentation/Others/Document Management.md
Enhanced documentation of Document Management endpoints by adding new implemented certificate endpoints
Feature development
n/a
=> docs(feat): adding new get document certificate endpoints

.github/dependabot.yml, CHANGELOG.md, docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md, package.json
https://github.com/eclipse-tractusx/portal/issues/318
=> build(2.0.0-rc1): merge release into main

DEPENDENCIES, docs/developer/Technical Documentation/Architecture/Security-Assessment.md
Update of the security assessment report.
Small changes related to the diagram, introduction of SSI Credential Issuer. Update of the assessment status and assessment date.
Based on the security assessment process and last meetings.
https://github.com/eclipse-tractusx/sig-release/issues/671
https://github.com/eclipse-tractusx/sig-security/issues/78#event-12783121209
=> docs: update Security-Assessment.md

CHANGELOG.md, package.json
https://github.com/eclipse-tractusx/portal/issues/325
=> build(2.0.0-rc2): merge release into main

docs/user/01. Onboarding/03. Registration Approval/04. Decline Application.md
Fix image path
URL is wrong
was introduced with https://github.com/eclipse-tractusx/portal-assets/pull/341
n/a
=> docs: fix image path

CONTRIBUTING.md, LICENSE_non-code, NOTICE.md
- update licensing and legal docs
#333
=> chore(TRG-7): update licensing and legal docs 

.github/workflows/build.yml, .github/workflows/release.yml, docs/developer/Technical Documentation/Dev Process/Dev-flow_deploy-dev-env.md, docs/developer/Technical Documentation/Dev Process/Dev-flow_git-diagram.md, docs/developer/Technical Documentation/Dev Process/How to contribute.md, docs/developer/Technical Documentation/Operations/Release-Process.md
get rid of dev branch: adjust workflow and documentation
https://github.com/eclipse-tractusx/portal/issues/243
=> chore(dev-flow): maintain latest changes in main branch

docs/user/00. Personas/Onboarding Service Provider (OSP).md
updated guide link in section "find & access osps"
guide url was faulty
resolves #358 
=> docs: Update Onboarding Service Provider (OSP).md

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/codeql.yml, .github/workflows/dependencies.yaml, .github/workflows/kics.yml, .github/workflows/pullRequest-lint.yaml, .github/workflows/release-release_candidate.yml, .github/workflows/release.yml, .github/workflows/release_candidate.yml, .github/workflows/trivy-main.yml, .github/workflows/trivy.yml, CHANGELOG.md, DEPENDENCIES, package.json, yarn.lock
Upgrade all packages found by dependabot that don't require license request.
This is a regular process and packages ws and braces had security findings.
n/a
=> chore(deps): upgrade dependabot findings

docs/user/04. App(s)/02. App Release Process/04. Technical Integration.md
Enhance app release documentation by adding for "Technical Integration" the technical user profile selection as well as improving the app role upload documentation.
Adding missing documentation and improving existing documentation
n/a
=> docs: update app release process Technical Integration.md

docs/user/05. Service(s)/02. Service Release Process/04. Technical Integration.md
Updated the technical integration documentation for the `Service Release Process`
Missing level of detail
n/a
=> docs: update service release process documentation 04. Technical Integration

docs/developer/Technical Documentation/Operator Wallet Setup/Initial Setup.md
Add documentation for the initial setup of the operator wallet
To give information on how to setup the application with an initial wallet for the operator
Refs: #362
=> docs: add documentation for initial wallet setup

CHANGELOG.md, package.json
https://github.com/eclipse-tractusx/portal/issues/380
=> build(2.1.0-rc1): bump version and update docs

docs/developer/Technical Documentation/Operator Wallet Setup/Initial Setup.md
Fixed the syntax for insert script in application_checklist
When we run this script it was giving syntax error
NA
=> fix(wallet): fixed the syntax error

docs/developer/Technical Documentation/Operator Wallet Setup/Initial Setup.md
Duplicate id(e85cf473-0321-4428-818a-3e595086ac94) removed and updated with new unique id for process steps table
This was giving error as id was same in process step table
NA
=> fix(operator): fix the duplicate id in process steps

CHANGELOG.md, package.json
* bump version for v2.2.0
* consolidated changelog for v2.2.0
prepare release
https://github.com/eclipse-tractusx/portal/issues/423
=> build(2.2.0): bump version and update docs

DEPENDENCIES, yarn.lock
Upgrade dependent libraries
Regular procedure to get latest bugfixes.
#405
=> chore: upgrade app dependencies

.github/workflows/trivy-main.yml, .github/workflows/trivy.yml, CHANGELOG.md, package.json
https://github.com/eclipse-tractusx/portal/issues/465
=> build(2.3.0-rc1): bump version and update docs

docs/admin/Interface Contracts/Offer-Autosetup.md
documentation of autosetup-process has been updated
respective documentation did contain incorrect information.
#374 
=> chore(offersubscription): update documentation of auto-subscription

.github/pull_request_template.md, CHANGELOG.md, CONTRIBUTING.md, package.json
https://github.com/eclipse-tractusx/portal/issues/482
=> build(2.3.0-rc2): bump version and update docs

CHANGELOG.md, package.json
https://github.com/eclipse-tractusx/portal/issues/482
=> build(v2.3.0): bump version and update docs

CHANGELOG.md
* update changelog for v2.4.0-RC1
To have all changes visible in the changelog
[#524](https://github.com/eclipse-tractusx/portal/issues/524)
=> build(2.4.0-rc1): update changelog

CHANGELOG.md, package.json
* update changelog
* bump version
To have a new version
[#524](https://github.com/eclipse-tractusx/portal/issues/524)
=> build(v2.4.0-RC1): bump version & update changelog

CHANGELOG.md, package.json
- update changelog
- bump version
To have a new version
eclipse-tractusx/portal#524
=> build(v2.4.0): bump version and update docs

CHANGELOG.md, docs/admin/Version Upgrade/portal-upgrade-details.md
* update changelog for v2.5.0-RC1
To have all changes visible in the changelog
N/A
=> build(2.5.0-rc1): update changelog and upgrade details

CHANGELOG.md, docs/admin/Version Upgrade/portal-upgrade-details.md, package.json
* bump version
To have a new version
N/A
=> build(v2.5.0-RC1): bump version
