eclipse-tractusx/portal-assets

developer/Technical Documentation/Others/Notifications.md
Enhanced notification documentation.
Endpoint Get: /api/notification/count-details got updated.
What got changed:
- add an additional key - actionRequiredUnread
Key/Attribute logic:
* actionRequired: only counts those "actionRequired" notifications, which are not done
* actionRequiredUnread: counts all unread "actionRequired" notifications
Enhancing the portal documentation of the notification service since the endpoint for /count-details got enhanced with additional attributes as well as an update of the business logic
n/a
=> docs(notifications): enhance endpoint notification count details

public/documentation/js/Settings.js, src/documentation/Release.js
Load data from eclipse repo
After the move of the container registry, the release process does occur exclusively in the tractusx GH org, due to that, the documentation pages must be loaded from the version tag in tractusx.
N/A
=> bugfix(documentation): load data from eclipse repo

developer/Technical Documentation/Identity & Access/05. Roles & Rights Concept.md
Update of the roles & rights matrix - technical user profiles
With the latest platform feature development and start to introduce dezentral Twin Registry the technical user permission matrix needed certain updates.
n/a
=> docs(technical-user-profiles): update tech user r&r matrix

developer/Technical Documentation/Dev Process/Dev-flow_deploy-dev-env.md
update dev process
push of init containers for iam to Docker Hub enables us to move away from the fork in catenax-ng in our dev process
Related PR: [n/a](https://github.com/eclipse-tractusx/portal-iam/pull/6)
=> docs(iam-working-mode-change): update dev process

.github/workflows/dependencies.yaml, .github/workflows/release.yml, DEPENDENCIES, NOTICE.md, scripts/check-dependencies.md
- add workflow to check 3rd party dependencies with the [Eclipse Dash License Tool](https://github.com/eclipse/dash-licenses)
- change dependencies file to '-summary' format from Dash Tool
**Due to the new format in the dependencies file: once this PR is merged into dev, all open feature branches should be rebased to dev, as the dependencies check will fail otherwise.**
- skip dispatch to portal-cd for hotfix in the release workflow
- update notice file
Dependencies check should be automated
Hotfix scenario not yet covered by release workflow
Notice file needs to be update due to new shared components repository
n/a
=> chore(workflows): add dependencies check and update release

developer/Technical Documentation/DB Views and Details/Data Management.md
Added users/client which are deployed as part of the portal release package.
Enable transparency inside the open source community when deploying/running the apps
n/a
=> Update Data Management.md

public/documentation/css/Chapter.css
reduce the height of side menu in the help section. allow scrolling to the bottom in the y axis
the menu of the help application exceeds the browser window and the user can not see the full content.
NA
=> bugfix(help side menu): fix scroll height

public/documentation/css/Chapter.css, public/documentation/js/Main.js
fix double scroll in side menu. show arrows at the top and bottom of the side menu
side menu shows double scroll
NA
=> bugfix(side menu): remove double scroll in side menu section

developer/03. User Management/03. Technical User/03. Create Technical User.md
Update technical user creation overlay
* styling
* adding the description of the technical user role (fetched from the same api endpoint as used to fetch the service account user roles)
Keeping documentation up to date
n/a
=> docs: enhance technical user service description

NOTICE.md, public/assets/images/content/CX.jpg.license, public/assets/images/content/GEC.jpg.license, public/assets/images/content/SAP.jpg.license, public/assets/images/content/Siemens.jpg.license
attribute logos in notice
[third-party-content](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#third-party-content)
n/a
=> chore: attribute logos in notice

.github/workflows/build.yml
build images also for arm64, in addition to amd64
enable localdev umbrella chart: arm64 images needed for usage on Mac
[localdev](https://github.com/eclipse-tractusx/portal-cd/pull/90)
=> build(arch): provide image also for arm64

DEPENDENCIES, developer/Technical Documentation/Architecture/operational-concept.md
Added description for a possible monitoring solution
To give a possible solution to operators on how a monitoring can be setup up
N/A - Jira Issue: CPLP-3332
=> chore: add monitoring documentation

.gitignore, package.json
add legal info (LICENSE NOTICE.md DEPENDENCIES SECURITY.md) at build
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05
https://github.com/eclipse-tractusx/portal-assets/issues/207
=> build(trg-7.05): add legal info at build

developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
Description
Adjusted the upgrade script for the keycloak roles
Why
Currently the role assignment is missing one role, this is added with this pr
Issue
N/A
=> chore: adjust technical user role documentation

src/documentation/Release.js
Remove static content folder from table of contents.
The static contents folder showed up in the list of chapters.
n/a
=> fix(docs-app): remove static folder

developer/Technical Documentation/Interface Contracts/BPDM.md, developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md, docs/03. User Management/01. User Account/04. Create new user account (bulk).md, docs/04. App(s)/02. App Release Process/index.md, docs/04. App(s)/06. App Change Process/07. Document Change.md, docs/09. Others/12. Offer Authentication Flow.md
Repair broken images in docs-app due to relative links.
Some images had a relative URL and were displayed in GitHub but not in the documentation app.
The docs app needs to be enabled for relative links.
ref: Jira CPLP-3561
=> fix(docs-apps): repair missing images

developer/Technical Documentation/DB Views and Details/Agreements - DB - View.md
Added 'Agreement' db table documentation
Docu was till now not existing
n/a
=> docs(developer): DB documentation for agreements

CHANGELOG.md, developer/Technical Documentation/DB Views and Details/Agreements - DB - View.md, package.json
Merge all related release changes to main
To have the latest changes available in main
N/A
=> build(1.8.0-RC1): merge release into main

public/assets/content/de/companyroles.json, public/assets/content/en/companyroles.json
add std library template information to the sections under company roles
std library information should be present in all the sections of company roles
NA
=> fix(standard library): add std library template

public/assets/content/de/companyroles.json, public/assets/content/de/dataspace.json, public/assets/content/en/companyroles.json, public/assets/content/en/dataspace.json
add title and description to the standard library section based on the company role
all company roles section displays same content
NA
=> fix(company roles): standard library title and description

docs/developer/Technical Documentation/Interface Contracts/Offer-Autosetup.md
Added customer details for the endpoint usage of /api/apps/start-autosetup
Missing details regarding needed endpoints to run the e2e process of the app subscription request configuration and activation via the endpoint /api/apps/start-autosetup
n/a
=> docs: add autosetup details

.conf/Dockerfile, docs/developer/Technical Documentation/Architecture/Development Concept.md, docs/developer/Technical Documentation/Architecture/operational-concept.md, scripts/repo.sh
remove references to catenax-ng and improve docs
https://github.com/eclipse-tractusx/portal-assets/issues/210
=> chore: remove references to catenax-ng and improve docs

CHANGELOG.md, public/documentation/index.html, public/documentation/js/Main.js, public/documentation/js/Settings.js, public/documentation/js/State.js, public/documentation/js/Toolkit.js
Fix links from documentation pages to GitHub
After restructuring of the docs folders the page / chapter links to GitHub were not working anymore.
ref. Jira CPLP-2332
=> fix(documentation): fix links to GitHub

.github/workflows/build.yml, .github/workflows/release-release_candidate.yml, .github/workflows/release.yml, .github/workflows/release_candidate.yml, .tractusx, NOTICE.md, README.md, docs/developer/Technical Documentation/Dev Process/Dev-flow_deploy-dev-env.md, docs/developer/Technical Documentation/Operations/Release-Process.md, docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131
=> chore(trg-2.04): change portal-cd references to portal

docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
updated the developer document for agreements
added the additional fields to the agreements and added new table agreement_statuses
#264
#255
=> docs: updated agreement details

docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
document for release 1.8.0 the change made in version upgrade doc for developer
company certificates - https://github.com/eclipse-tractusx/sig-release/issues/326
new feature database tables for company certificate reference added.
Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.
#264
#255
=> docs:  changes in version upgrade doc for company certificates

docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
technical documentation has been added that describe the details of new OnboardingServiceProvider EncryptionConfig.
To enable a stronger encryption for OnboardingServiceProvider ClientSecrets https://github.com/eclipse-tractusx/portal-backend/pull/531 includes changes that allow the configuration of encryption-algorithm properties cipher-mode, padding-mode and encryption-key. Multiple configuration can be specified. To ensure existing data can be decrypted after the upgrade the first configuration must match the one that was being used before the change.
https://github.com/eclipse-tractusx/portal-backend/issues/437
=> docs(upgrade): add documentation of new encryption-configuration for osp

src/documentation/Release.js
Use file handle for all file operations
Using a file handle ensures the file hasn't beed modified or deleted after checks.
[#114](https://github.com/eclipse-tractusx/portal-assets/security/code-scanning/114)
=> fix(security): fix file system race condition

docs/developer/Technical Documentation/Interface Contracts/BPDM.md
BPDM UniqueIdentifier mapping added (Interface between BPDM and Portal) used for registration and portal flows.
Missing documentation
n/a
=> docs: add bpdm mapping table

docs/user/03. User Management/03. Technical User/02. Create Technical User.md
Updated technical user documentation of supported roles fitting to 24.05. release
Change of supported technical user composite roles
n/a
=> docs: updated technical user role(s) supported

CHANGELOG.md, package.json
https://github.com/eclipse-tractusx/portal/issues/379
=> build(2.1.0): bump version and update docs

docs/developer/Technical Documentation/Operator Wallet Setup/Initial Setup.md
adjust script to add the application to create the initial operator wallet
the script creates the application in state confirmed, but it must be in state `SUBMITTED` to be picked up by the application checklist process
Refs: #362
=> fix: adjust initial wallet script

docs/developer/09. Process Workers/index.md
Adjust the links from index to each process worker detail file
The links are currently broken
N/A
=> docs(processWorker): adjust links to process workers

docs/developer/Technical Documentation/Operations/Release-Process.md
update release process for localdev version bump
https://github.com/eclipse-tractusx/portal/issues/399
=> docs(release): update process for localdev version bump

docs/developer/03. User Management/03. Technical User/04. Delete Technical User.md
Adjust the technical user delete documentation
The process was adjusted for external users
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/950
https://github.com/eclipse-tractusx/portal-backend/pull/956
=> docs: adjust delete technical user documentation

docs/developer/Technical Documentation/Operator Wallet Setup/Initial Setup.md
Adjusted the description of the initial wallet setup
To describe the new process
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/1003
=> docs: adjusted documentation for wallet seeding

CHANGELOG.md, public/assets/content/de/dataspace.json, public/assets/content/en/dataspace.json
fixed incorrect Manage UseCase Credentials url.
Need fix the Manage UseCase Credentials url because the current url not working.
https://github.com/eclipse-tractusx/portal-frontend/issues/1152
=> fix(Use Case Participation): incorrect Manage UseCase Credentials url

docs/user/00. Personas/Onboarding Service Provider (OSP).md, docs/user/01. Onboarding/01. Registration Invite/02. FAQ.md, docs/user/01. Onboarding/02. Registration/03. Add Additional User(s).md, docs/user/01. Onboarding/02. Registration/04. Company Role & Consent.md, docs/user/01. Onboarding/02. Registration/05. Document Upload.md, docs/user/01. Onboarding/02. Registration/06. Verify Registration Data.md, docs/user/01. Onboarding/02. Registration/07. FAQ.md, docs/user/01. Onboarding/03. Registration Approval/02. View Company Application(s).md, docs/user/01. Onboarding/03. Registration Approval/03. Registration Approval Process.md, docs/user/01. Onboarding/03. Registration Approval/04. Decline Application.md, docs/user/01. Onboarding/03. Registration Approval/05. FAQ.md, docs/user/01. Onboarding/04. OSP/01. Onboarding with an OSP.md
Several typos and grammar issues, were fixed in docs/user/00.&01.
For better readability
n/a
=> docs(user): fix of typos and grammar in 00. and 01.

docs/admin/Version Upgrade/portal-upgrade-details.md
add missing versions to upgrade details
To have all versions documented
https://github.com/eclipse-tractusx/portal/issues/482
=> docs: adjust version upgrade details

docs/admin/Interface Contracts/Offer-Autosetup.md
Updated the request body sent in the callback URL 
Now the app can have multiple technical users, so this fix is to enable the code to send multiple technical users to the callback URL.
[#1307](https://github.com/eclipse-tractusx/portal-backend/issues/1307)
NOTE: Please merge only after [PR-1318](https://github.com/eclipse-tractusx/portal-backend/pull/1318) has been merged
=> docs(offersubscription): fixed the callback url post body

docs/admin/Interface Contracts/Offer-Autosetup.md
* add documentation for the callbackUrl removal of an offer provider
To provide information what happens when an offer provider removes his callback url
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/1175
=> docs(autoSetup): add callback url removal
